config/routes.rb
Rails.application.routes.draw do
  resources :brochures do
    get :fill_in
    post :answer_brochure
    get :results
  end
  devise_for :users, :controllers => { :confirmations => "confirmations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "dashboard#index"
  resources :users do
    delete :destroy
  end


  resource :policies
  get '/security/privacy_policy/', to: 'policies#privacy_policy'
  get '/security/terms_and_conditions/', to: 'policies#terms_and_conditions'
  get '/security/cookies/', to: 'policies#cookie_policy'
  get '/security', to: 'securities#index', :as => :security
  as :user do
    put '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end
  post '/new_user', to: 'users#create'

  get '/form_builder', to: 'form_builder#index', :as => :form_builder
  get '/form_builder/new', to: 'form_builder#new'


  resources :surveys
  get '/assign_brochure', to: 'assign#index', :as => :assign
  get '/search_members', to: 'assign#search_members'
  post '/get_brochure', to: 'assign#get_brochure'
  post '/assign_members', to: 'assign#assign_members'

  resources :brochure_members

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :check_user_details

  def check_user_details
    @user = current_user
    if @user.try(:first_name).blank?
      flash[:error] = "Trebuie sa completezi detaliile profilului intai!"
      redirect_to edit_user_path(@user) and return
    end
  end

  def index
    @user = current_user
    @surveys = Survey.all
    @brochures = Brochure.all

    @completed_brochures = BrochureMember.where(user_id: @user.id).where(answered: true)
    @uncompleted_brochures = BrochureMember.where(user_id: @user.id).where(answered: false).order("created_at DESC")
    @brochures = Brochure.all.index_by(&:id)

    @total_submissions = BrochureAnswer.all.group_by{|r| [r[:user_id], r[:brochure_id]]}.count
  end
end

app/views/dashboard/_admin.html.haml
.row.d-flex.justify-content-between
  .col-xs-4.col-lg-3.border_custom{style: "padding:10px"}
    %h4
      TOTAL COMPLETARI
      %i.fa.fa-check-square.pull-right.fa-lg.color_purple{style: "padding:10px"}
    %h5.color_gray
      #{@total_submissions}
  .col-xs-4.col-lg-3.border_custom{style: "padding:10px"}
    %h4
      TOTAL SCENARII
      %i.fa.fa-copy.pull-right.fa-lg.color_purple{style: "padding:10px"}
    %h5.color_gray
      #{@surveys.count}
  .col-xs-4.col-lg-3.border_custom{style: "padding:10px"}
    %h5
      TOTAL BROSURI
      %i.fa.fa-book.pull-right.fa-lg.color_purple{style: "padding:10px"}
    %h7.color_gray
      #{@brochures.count}

.row{style: "margin-top: 100px"}
  .col-xs-12.col-lg-12
    = column_chart [["Ianuarie", [*20..300].sample], ["Februarie", [*20..300].sample], ["Martie", [*20..300].sample], ["Aprilie", [*20..300].sample], ["Mai", [*20..300].sample], ["Iunie", [*20..300].sample], ["Iulie", [*20..300].sample], ["August", [*20..300].sample], ["Spetembrie", [*20..300].sample], ["Octombrie", [*20..300].sample], ["Noiembrie", [*20..300].sample], ["Decembrie", [*20..300].sample]], colors: ["#B48DF8", "#FF0000"], library: {backgroundColor: "#B48DF8"}, width: "100%"

app/views/dashboard/_user.html.haml
.row
  .col-xs-8.col-lg-8
    .row
      .col-xs-6.col-lg-6.border_custom{style: "padding:10px"}
        %h4
          BROSURI COMPLETATE
          %i.fa.fa-check-square.pull-right.fa-lg.color_purple{style: "padding:10px"}
        %h5.color_gray
          #{@completed_brochures.count}
  .col-xs-3.col-lg-3.border_custom{style: "padding:10px"}
    %h4
      Citatul zilei
      %i.fa.fa-quote-right.pull-right.fa-lg.color_purple{style: "padding:10px"}
    - quote = quotes.sample
    %h5.color_gray
      #{quote[0]}
    %h5.color_gray.pull-right
      #{quote[1]}
.row{style: "margin-top: 100px"}
  .col-xs-12.col-lg-12
    %h4
      BROSURI NOI
  - if @uncompleted_brochures.first(2).present?
    - @uncompleted_brochures.first(2).each do |ub|
      - brochure = @brochures[ub.brochure_id]
      .col-xs-10.col-lg-10{style: "margin-top: 20px"}
        .row.border_custom{style: "padding:15px;"}
          .col-xs-3.col-lg-3{style: "padding-top: 20px"}
            %h5
              #{brochure.try(:title)}.
          .col-xs-2.col-lg-2.d-flex.flex-column{style: "padding-top: 5px"}
            %span #{ub.created_at.try(:strftime, "%d/%m/%Y")}
            %span{style: "font-size:11px; font-style: italic; color: lightgray;"} Primit
          .col-xs-3.col-lg-3.d-flex.flex-column{style: "padding-top: 5px"}
            %span #{brochure.try(:author) || "Claudia Rus"}
            %span{style: "font-size:11px; font-style: italic; color: lightgray;"} Autor
          .col-xs-3.col-lg-3.pull-right.d-flex{style: "padding-top: 10px"}
            = button_to  "Vizualizeaza", brochure_path(brochure, brochure_id: brochure.id), method: :get, "data-toggle" => "tooltip", class:"btn btn-default btn_big_custom custom_btn btn_grey", style: "font-size: 20px!important;"
            = button_to  "Completeaza", brochure_fill_in_path(brochure), method: :get, class:"btn btn-default btn_big_custom custom_btn btn_orange", style: "font-size: 20px!important;"


  - else
    .col-xs-10.col-lg-10
      %h5.add_padding_left_10
        Nu exista brosuri noi

.row{style: "margin-top: 20px"}
  .col-xs-12.col-lg-12{style: "margin-bottom: 15px"}
    %h4
      BROSURI DISPONIBILE

  - if @uncompleted_brochures.drop(2).first(2).present?
    - @uncompleted_brochures.drop(2).first(2).each do |ub|
      - brochure = @brochures[ub.brochure_id]
      .col-xs-10.col-lg-10{style: "margin-top: 20px"}
        .row.border_custom{style: "padding:15px;"}
          .col-xs-3.col-lg-3{style: "padding-top: 20px"}
            %h5
              #{brochure.try(:title)}
          .col-xs-2.col-lg-2.d-flex.flex-column{style: "padding-top: 5px"}
            %span #{ub.created_at.try(:strftime, "%d/%m/%Y")}
            %span{style: "font-size:11px; font-style: italic; color: lightgray;"} Primit
          .col-xs-3.col-lg-3.d-flex.flex-column{style: "padding-top: 5px"}
            %span #{brochure.try(:author) || "Claudia Rus"}
            %span{style: "font-size:11px; font-style: italic; color: lightgray;"} Autor
          .col-xs-3.col-lg-3.pull-right.d-flex{style: "padding-top: 10px"}
            = button_to  "Vizualizeaza", brochure_path(brochure, brochure_id: brochure.id), method: :get, class:"btn btn-default btn_big_custom custom_btn btn_grey", style: "font-size: 20px!important;"
            = button_to  "Completeaza", brochure_fill_in_path(brochure), method: :get, class:"btn btn-default btn_big_custom custom_btn btn_orange", style: "font-size: 20px!important;"


  - else
    .col-xs-10.col-lg-10
      %h5.add_padding_left_10
        Nu exista alte brosuri disponibile

app/views/dashboard/index.html.haml
- if is_admin?
  = render partial: 'dashboard/admin'
- else
  = render partial: 'dashboard/user'