config/routes.rb
Rails.application.routes.draw do
  resources :brochures do
    get :fill_in
    post :answer_brochure
    get :results
  end
  devise_for :users, :controllers => { :confirmations => "confirmations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "dashboard#index"
  resources :users do
    delete :destroy
  end


  resource :policies
  get '/security/privacy_policy/', to: 'policies#privacy_policy'
  get '/security/terms_and_conditions/', to: 'policies#terms_and_conditions'
  get '/security/cookies/', to: 'policies#cookie_policy'
  get '/security', to: 'securities#index', :as => :security
  as :user do
    put '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end
  post '/new_user', to: 'users#create'

  get '/form_builder', to: 'form_builder#index', :as => :form_builder
  get '/form_builder/new', to: 'form_builder#new'


  resources :surveys
  get '/assign_brochure', to: 'assign#index', :as => :assign
  get '/search_members', to: 'assign#search_members'
  post '/get_brochure', to: 'assign#get_brochure'
  post '/assign_members', to: 'assign#assign_members'

  resources :brochure_members

end

app/controllers/form_builder_controller.rb
class FormBuilderController < ApplicationController
  def index

  end

  def new
    @titles = DetailForm.pluck(:title)
  end
end

app/views/form_builder/index.html.haml
.row
  .col-12.no_padding_left
    = link_to "Pagina principala", root_path, :method => :get, class: "top_link_grey"
    %i.fa.fa-chevron-right.color_grey
    %span.color_purple Detaliile profilului
.col-lg-12.add_margin_top_20#survey_index_container
  - if @details.blank?
    Nu exista niciun profil customizat
  - else
    - @details.each do |detail_form|
      .row.add_margin_top_10.add_padding_bottom_10.border_custom.add_padding_top_15
        .col-xs-12.col-lg-3
          %h4.bold{style: "width: 500px"}
            #{detail_form.title}
        .action_buttons
          -# = link_to "", brochure_path(id: detail_form.id), method: :delete, data: { confirm: "Are you sure?" }, "data-remote" => "true", class: "fa fa-trash color_red font_size_30 pull-right", "data-toggle" => "tooltip", title: "Sterge"
          -#
          -# - if detail_form.sent_at.blank?
          -#   %a.fa.fa-pencil.color_lightskyblue.font_size_30.pull-right.add_margin_right_15{href: edit_brochure_path(brochure), method: :get, "data-toggle" => "tooltip", title: "Editeaza"}
          -# - else
          -#   %a.fa.fa-pencil.color_lightskyblue.disabled.font_size_30.pull-right.add_margin_right_15{href: edit_brochure_path(brochure), method: :get, "data-toggle" => "tooltip"}
          -#     %i.gga-info-circle.cursor_pointer{'data-toggle' => "tooltip", title: "Survey has already been sent and cannot be edited anymore."}
          -# %a.fa.fa-line-chart.color_green.font_size_30.pull-right.add_margin_right_15{href: brochure_results_path(brochure), method: :get, "data-toggle" => "tooltip", title: "Vezi rezultatele"}
          -# %a.fa.fa-eye.color_purple.font_size_30.pull-right.add_margin_right_15{href: brochure_path(brochure), method: :get, "data-toggle" => "tooltip", title: "Previzualizare"}

.row.fixed_survey_bar.background_light_grey
  .col-xs-12.col-sm-12
    .btsp_custom_tabs_menu
    .add-margin-right-0.pull-right
      = link_to  "Profil nou", form_builder_new_path, class:"btn btn-default btn_big_custom custom_btn btn_orange"
    .add-margin-right-0.pull-left



:javascript
  window.crm.surveys.init();
  window.crm.new_design_shared.applyCustomScrollbar("#survey_index_container");

app/views/form_builder/new.html.haml
.row
  .col-12.no_padding_left
    = link_to "Pagina principala", root_path, :method => :get, class: "top_link_grey"
    %i.fa.fa-chevron-right.color_grey
    = link_to "Detaliile profilului", form_builder_path, :method => :get, class: "top_link_grey"
    %i.fa.fa-chevron-right.color_grey
    %span.color_purple Configureaza Profil
.row.add_margin_top_20
  .col-lg-7.col-xs-4.popup_form_size.custom_width_30
    %h6 Profil pentru urmatoarea categorie de membrii:
  .col-lg-4.no_padding{style:"width: 300px!important"}
    = select_tag :title, options_for_select(options_for_members.reject{|m| @titles.include? m.second}, selected: "militari"), class: "form-control js-example-basic-single", onchange: "selectBrochure()"

.row.d-flex.add_margin_top_20
  .col-7
    - [*0..50].each_with_index do |row, index|
      .col-12.d-flex{'data-row-form' => index}
        .col-11.form_row.border{class: ("hidden add_margin_top_10" if index != 0), style: "border-radius: 4px"}
          .row.d-fex.w-100.h-100.add_padding_10{'data-row' => index, :ondragover => "allowDrop(event)", :ondrop => "drop(event)"}
        .col-1.fa.fa-trash.delete_row.color_red{class: (index != 0 ? "hidden add_margin_top_20" : "add_margin_top_10"), 'data-row' => index}
  .col-4.d-flex.flex-column.add_padding_5.border{style: "border-radius: 4px"}
    .filed.add_padding_5.border.d-flex#label{style: "border-style: dotted!important", :draggable => "true", :height => "100", :ondragstart => "drag(event)", :width => "336"}
      %label.add_margin_right_10 Text
      %input.add_margin_right_10#label_title{style: "width: 200px; height: 30px", :oninput => "label_text(event)"}
    .filed.add_padding_5.border.add_margin_top_10#input{style: "border-style: dotted!important", :draggable => "true", :height => "100", :ondragstart => "drag(event)", :width => "336"}
      %input.add_margin_right_10{style: "width: 100px; height: 30px"}

.row.add-margin-top-20
  %button#add_row{type: 'button', class: "pull-left btn btn-default btn_big_custom custom_btn btn_orange", style:"border-radius:4px"} Adauga scenariu


:javascript
  window.gems.email_templates.init();
  $(document).ready(function() {
    $('.js-example-basic-single').select2();
  });

  function selectBrochure() {
    window.gems.email_templates.get_brochure();
  }
  function allowDrop(ev) {
    ev.preventDefault();
  }

  function label_text(ev) {
    ev.preventDefault();
    input = $(ev.target)
    text = input.val()
    $(input.parent().children()[0]).html(text);

  }

  function drag(ev) {
    ev.dataTransfer.setData("text", ev.target.id);
  }

  function drop(ev) {
    ev.preventDefault();
    var data = ev.dataTransfer.getData("text");

    clone_node = $($(document.getElementById(data)).children()[0]).clone(true, true);
    column = $(ev.target).children().length
    row = $(ev.target).attr('data-row')
    clone_node.attr('id', "row_"+row+"_column_"+column)
    $(ev.target).append(clone_node);
  }