config/routes.rb
Rails.application.routes.draw do
  resources :brochures do
    get :fill_in
    post :answer_brochure
    get :results
  end
  devise_for :users, :controllers => { :confirmations => "confirmations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "dashboard#index"
  resources :users do
    delete :destroy
  end


  resource :policies
  get '/security/privacy_policy/', to: 'policies#privacy_policy'
  get '/security/terms_and_conditions/', to: 'policies#terms_and_conditions'
  get '/security/cookies/', to: 'policies#cookie_policy'
  get '/security', to: 'securities#index', :as => :security
  as :user do
    put '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end
  post '/new_user', to: 'users#create'

  get '/form_builder', to: 'form_builder#index', :as => :form_builder
  get '/form_builder/new', to: 'form_builder#new'


  resources :surveys
  get '/assign_brochure', to: 'assign#index', :as => :assign
  get '/search_members', to: 'assign#search_members'
  post '/get_brochure', to: 'assign#get_brochure'
  post '/assign_members', to: 'assign#assign_members'

  resources :brochure_members

end

app/controllers/assign_controller.rb
class AssignController < ApplicationController
  before_action :check_user_details
  def check_user_details
    @user = current_user
    if @user.try(:first_name).blank?
      flash[:error] = "Trebuie sa completezi detaliile profilului intai!"
      redirect_to edit_user_path(@user) and return
    end
  end

  # GET /websites
  # GET /websites.json
  def index
    @specific_members = User.all
    @brochure = nil
    @preview = true
    @scenarios_ids = []
    @scenarios = []
    @questions = []
    @answers = []
    @user = current_user
  end

  def show

  end

  def search_members

  end

  def get_brochure
    @brochure = Brochure.find(params[:brochure_id])
    @preview = true
    @scenarios_ids = RelationBrochureScenarios.where(brochure_id: @brochure.id).pluck(:survey_id)
    @scenarios = Survey.includes(:questions => :options).order('questions.order ASC, options.order ASC').where(id: @scenarios_ids)
    @questions = Question.where(survey_id: @scenarios_ids).sort_by(&:order).group_by(&:survey_id)
    @answers = []
    @user = current_user
  end

  def assign_members
    brochure_id = params["brochure"]

    if params["specific_members"] == "on"
      members_ids = params["specific_members"].split(',')
    else
      members_ids = User.all.pluck(:id)
    end

    members_ids.each do |member|
      BrochureMember.create({user_id: member, brochure_id: brochure_id, answered: false})
    end

    flash[:notice] = 'Brosura trimisa!'
    redirect_to assign_path and return
  end



  private


    # Only allow a list of trusted parameters through.
    def security_params
      params.fetch(:security, {})
    end
end

app/views/assign/_body_specific_members.html.haml
- if @specific_members.blank?
  .col-lg-12.no_padding
    .col-lg-12.col-xs-12.no_padding.add-margin-bottom-20
    %span Nu exista membri momentan
- else
  .col-lg-12.no_padding
    = form_tag search_members_path, :method => 'GET', :id => "search_members_email_form", :remote => true do
      .col-lg-12.col-xs-12.no_padding.add-margin-bottom-20
        .col-lg-12.col-xs-12.no_padding.custom_table_container#members_email{style: "max-height: 350px; min-height: 300px"}
          = render partial: 'member_list_modal'
      -#.col-lg-12.add-margin-top-10.add-margin-bottom-20
      -#  .paginate_members.pull-right#select_page_member
      -#    = render partial: 'layouts/paginate', locals: {items: @specific_members, remote_pagination: true}
:javascript
  window.gems.email_templates.emailTemplateSpecificMembersModal();

app/views/assign/_member_list_modal.html.haml
.tableFixHead
  %table.table.table-striped.custom_table2
    %thead
      %tr
        %th.background_light_gray.custom_vertical_align_middle{style: "z-index: 2;"}
        %th.background_light_gray.custom_vertical_align_middle PRENUME
        %th.background_light_gray.custom_vertical_align_middle NUME DE FAMILEI
        %th.background_light_gray.custom_vertical_align_middle EMAIL
        %th.background_light_gray.custom_vertical_align_middle TELEFON
    %tbody
      - @specific_members.each do |member|
        %tr
          %td.no_padding_top
            .custom-control.custom-checkbox.d-flex.select_member_checkbox{id: "#{member.id}"}
              = text_field_tag "checkbox_#{member.id}", "", class: 'custom-control-input', type: "checkbox"
              %label.custom-control-label{:for => "checkbox_#{member.id}"}

            -#.form-group.center_form_group_items
            -#  .checkbox.checkbox_select
            -#    %input{id: , class: "form-control assign ", :, :type => "checkbox"}
            -#    %label
          %td #{member.first_name}
          %td #{member.last_name}
          %td #{member.email}
          %td #{member.phone}

app/views/assign/_modal_select_members.html.haml
#modalSelectMembers.modal.btsp_fheader_table_container.fade{"aria-labelledby" => "myModalLabel", :role => "dialog"}
  .modal-dialog.body{:role => "document", :tabindex => "-1", style: "min-width: 1050px!important"}
    .modal-content.body.orders.custom_modal_content
      .modal-header.no_border.no_padding
        .col-lg-12.body.orders.custom_modal_header
          %h4.modal-title.form_new_edit.no-margin.hidden#specific_golfers_modal SELECTEAZA MEMBRII...
          %h4.modal-title.form_new_edit.no-margin.hidden#select_by_modal SELECT BY...
      .modal-body.modal_body_finalize_demo
        .email_select_by.hidden
          -# = render partial: 'email_templates/body_select_by_members'
        .specific_golfers_align.email_select_golfers.hidden
          = render partial: 'body_specific_members'
      .modal-footer.no_border.no_padding.add_padding_top_15
        .col-lg-12.body.orders.custom_modal_footer
          .left
            %button.btn.btn-default.custom_btn{"data-dismiss" => "modal", :type => "button"} Inchide
          .right
            %button.btn.btn-default.custom_btn.btn_orange#mark_selected_members{"data-dismiss" => "modal", :type => "button", remote: true} Salveaza

app/views/assign/get_brochure.js.haml
= render partial: 'brochures/user_brochure'

app/views/assign/index.html.haml
= form_tag assign_members_path, :method => 'post', id: 'assign_members' do
  .row
    .col-12
      = link_to "Pagina principala", root_path, :method => :get, class: "top_link_grey"
      %i.fa.fa-chevron-right.color_grey
      %span.color_purple Trimite brosuri
  .row
    .col-12
      .h6.add_padding_top_15
        %b Trimite brosuri:
        .col-lg-12.no_padding.d-flex
          .col-lg-3.no_padding_left
            %input#checkbox_all_golfers{:type => "radio", name: "all_golfers"}
            %label.add-margin-left-10{:for => "checkbox_all_golfers"} Tuturor membrilor
          .col-lg-3.no_padding_left
            %input#checkbox_specific_golfers{:type => "radio", name: "specific_golfers"}
            %label.add-margin-left-10{:for => "checkbox_specific_golfers"} Anumiti membri...
            %a.link.hidden#edit_specific_golfers Editeaza
            = hidden_field_tag '', '', id: "specific_golfers_modal"
            = hidden_field_tag :specific_members, "",  value: ""
  .row
    .col-12.add_margin_top_20
      .h6.add_padding_top_15
        %b Selecteaza brosura:
        .col-lg-12.no_padding{style:"width: 300px!important"}
          = select_tag "brochure", options_for_select(options_for_brochure, selected: "0"), class: "form-control js-example-basic-single", onchange: "selectBrochure()"
  .row{style: "margin-bottom: 100px"}
    .col-12.add_margin_top_20#brochure_form
      = render partial: 'brochures/user_brochure'

  = render partial: "modal_select_members"

  .row.fixed_survey_bar.background_light_grey
    .col-xs-12.col-sm-12
      .btsp_custom_tabs_menu
      .add-margin-right-0.pull-right
        %button.btn.btn-default.btn_big_custom.custom_btn.btn_orange#assign Asigneaza brosura

      .add-margin-right-0.pull-left
:javascript
  window.gems.email_templates.init();
  $(document).ready(function() {
    $('.js-example-basic-single').select2();
  });

  function selectBrochure() {
    window.gems.email_templates.get_brochure();
  }