config/routes.rb
Rails.application.routes.draw do
  resources :brochures do
    get :fill_in
    post :answer_brochure
    get :results
  end
  devise_for :users, :controllers => { :confirmations => "confirmations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "dashboard#index"
  resources :users do
    delete :destroy
  end


  resource :policies
  get '/security/privacy_policy/', to: 'policies#privacy_policy'
  get '/security/terms_and_conditions/', to: 'policies#terms_and_conditions'
  get '/security/cookies/', to: 'policies#cookie_policy'
  get '/security', to: 'securities#index', :as => :security
  as :user do
    put '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end
  post '/new_user', to: 'users#create'

  get '/form_builder', to: 'form_builder#index', :as => :form_builder
  get '/form_builder/new', to: 'form_builder#new'


  resources :surveys
  get '/assign_brochure', to: 'assign#index', :as => :assign
  get '/search_members', to: 'assign#search_members'
  post '/get_brochure', to: 'assign#get_brochure'
  post '/assign_members', to: 'assign#assign_members'

  resources :brochure_members

end

app/models/survey.rb
class Survey < ApplicationRecord
  include Rails.application.routes.url_helpers

  has_many :questions, dependent: :destroy, inverse_of: :survey
  accepts_nested_attributes_for :questions, allow_destroy: true, reject_if: proc { |attributes| attributes['title'].blank? }

  def self.dummy_structure c
    s = Survey.last
    m = User.first

    if s.present? && m.present?
      dummy_survey_link = s.link_for_member m
    else
      dummy_survey_link = "#"
    end

    Struct.new(:title, :description, :logo, :customer, :link, :link_for_member) \
          .new('Survey Test', 'Description test', 'Logo', c, 'url_preview_to_survey', dummy_survey_link)
  end

  def link_for_member member

    protocol = ActionMailer::Base.default_url_options[:protocol]

    host = ActionMailer::Base.default_url_options[:host]

    host = ("www." + host) if host == "gsgstaging.com"
    host = ("golfshop." + host) if host == "golfgenius.com"
    return "#{protocol}://#{host}#{fill_survey_member_survey_path(self.id, member.id, self.id)}"
  end

  def survey_percentage nb_responses
    nb_responses == 0 || self.nb_emails_sent_to_members == 0 ? 0 : (nb_responses / self.nb_emails_sent_to_members.to_f * 100).round(2)
  end


  def self.surveys_for_select surveys = []

    surveys_for_select =  Array.new()
    surveys_for_select << ["Select existing survey..", 0]

    surveys.each do |survey|
      surveys_for_select << ["#{survey.title}", survey.id.to_s]
    end
    return surveys_for_select
  end

  def first_sync_name
    first_sync ? "Sync Answers" : "Import Answers"
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  require 'open-uri'
  include ApplicationHelper

  skip_authorization_check :only => [:fill_survey, :submit_survey, :survey_sent]

  def index
    @surveys = Survey.includes(:questions).order(id: :asc)
    @survey_brochures = RelationBrochureScenarios.all.group_by(&:survey_id)
  end

  def new
    @survey = Survey.new
    respond_to do |format|
      format.js {render "surveys/new"}
      format.html
    end
  end

  def edit
    @survey = Survey.includes(:questions => :options)
                  .where(id: params[:id])
                  .order('questions.order ASC, options.order ASC').to_a.first

    redirect_to surveys_path and return if @survey.blank?

    respond_to do |format|
      format.js {render "surveys/edit"}
      format.html
    end
  end

  def show
    @answers = []
    @survey = Survey.includes(:questions => :options).order('questions.order ASC, options.order ASC').find_by_id(params[:id])

    @questions = Question.where(survey_id: params[:id]).order(:order)

    redirect_to surveys_path and return if @survey.blank?
  end

  def update
    @survey = Survey.find(params[:id])
    survey_attrs = survey_params

     #update options order
    survey_attrs[:questions_attributes].each do |key, question|
      if question[:options_attributes].present? && ((question["question_type"] == "multiple_answers") || (question["question_type"] == "multiple_choice"))
        question[:options_attributes].each do |key_option, option|
          if option['title'].present? && option['_destroy'] == "false"
            option['order'] = question[:options_attributes].to_h.find_index{|k,_| k == key_option} + 1
          end
        end
      end
    end

    @survey.update(survey_attrs)

    redirect_to surveys_path
  end

  def create
    survey_attrs = survey_params

    suvey = Survey.create

    #set options order
    survey_attrs[:questions_attributes].each do |key, question|
      if question[:options_attributes].present? && ((question["question_type"] == "multiple_answers") || (question["question_type"] == "multiple_choice"))
        question[:options_attributes].each do |key_option, option|
          if option['title'].present? && option['_destroy'] == "false"
            option['order'] = question[:options_attributes].to_h.find_index{|k,_| k == key_option} + 1
          end
        end
      end
    end

    survey_attrs["author"] = current_user.full_name
    if suvey.update survey_attrs
      flash[:notice] = "Successfully created."
      redirect_to surveys_path and return
    else
      @survey = Survey.new
      render 'new'
    end

  end

  def destroy
    @survey = Survey.find(params[:id]).delete
    flash[:notice] = "Stergerea s-a efectuat cu success."
    redirect_to surveys_path and return
  end

  def send_survey
    @survey = Survey.find_by_id(params[:id])
    @active_filters = "all"
    @metadata_member = Metadatum.where(datatype: "member").order(display_order: :asc)
    @email_template_member_fields = Metadatum.custom_fields_template(["member", "Customer", "member"], @metadata_member)
    @filters_member_fields = Metadatum.custom_fields_template(["member", "", "member"], @metadata_member)
    @specific_members = User.active.order("last_name asc, first_name asc").paginate(page: params[:page], per_page: 100)

    #link might point to new even if one is created already
    @email_template = EmailTemplate.new(EmailTemplate::GSG_DEFAULT_TEMPLATES.deep_dup[:survey])
    @email_template.email_template_type = "survey"

    respond_to do |format|
      format.html
      format.js { render 'email_templates/members_list_modal' }
    end
  end

  def get_member_metatum_values
    field = params['field']
    if field
      custom_field_id = field.split('.')[1].to_i
      membermetada = MemberMetadatum.where(metadatum_id: custom_field_id).where("value is not NULL AND value <> '' ").select('DISTINCT value')
      custom_field_values = []
      membermetada.each do |m|
        custom_field_values << ["#{m.value}", m.value]
      end
      respond_to do |format|
        format.js {render "surveys/get_member_metatum_values", locals: {custom_field_values: custom_field_values}}
      end
    end
  end

  def sync_results_page

    @survey = Survey.find_by_id(params[:id])
    @column_matching = []
    @column_unmatching = []
    @column_new = []

    #all metadata
    metadata_name = Metadatum.includes(:member_profile_category).where(datatype:  "member").pluck(:id, :name, :member_profile_category_id)
    member_metadata_profile_alfa = MemberProfileCategory
    member_metadata_profile_names = member_metadata_profile_alfa.pluck(:id, :name)

    questions = Question.where(survey_id: @survey.id).pluck(:id, :title)

    questions.each do |q|
      name_match = q[1].downcase.strip
      #matching fields
      if (db_club_value = (metadata_name.select{|m| name_match == m[1].downcase}.first || metadata_name.select{|m| name_match[m[1].downcase] || m[1].downcase[name_match] }.first)).present?
        if db_club_value[2].present?
          @column_matching << {your_id: q[0], your_name: q[1], our_id: db_club_value[0], our_name: db_club_value[1]+" (#{member_metadata_profile_names.select{|m| m[0] == db_club_value[2]}[0][1].capitalize})"}
        else
          @column_matching << {your_id: q[0], your_name: q[1], our_id: db_club_value[0], our_name: db_club_value[1]}
        end
        metadata_name = metadata_name.reject{|m| m[0] == db_club_value[0]}
      else
        @column_unmatching << {your_id: q[0], your_name: q[1], our_id: nil, our_name: nil}
      end
    end

    #available custom fields to match
    @options_for_unmachting = []
    @options_for_unmachting_final = {}
    @options_for_unmachting_final["Do not import"] = [["Skip Custom Field", "skip"]]
    @options_for_unmachting_final["New Custom Field"] = [["Create Custom Field", "new"]]

    metadata_name.each do |m|
      if m[2].present?
        @options_for_unmachting << ["#{m[1].capitalize} (#{member_metadata_profile_names.select{|mp| mp[0] == m[2]}[0][1].capitalize})", m[0]]
      else
        @options_for_unmachting << ["#{m[1].capitalize}", m[0]]
      end
    end

    @options_for_unmachting_final["Match to"] =  @options_for_unmachting


    m_p_category = member_metadata_profile_alfa.where("LOWER(name) = '#{@survey.title.gsub('\'', "''").downcase}'")
                       .first
    if m_p_category.blank?
      m_p_category = MemberProfileCategory.new({name: @survey.title,
                                                display_order: (member_metadata_profile_alfa.maximum(:display_order) || 0) + 1})
      m_p_category.save()
    end

    @member_profile_default_category = m_p_category.try(:id)

    @member_profile_categories = member_metadata_profile_alfa.map{|c| ["#{c.name.capitalize}",c.id]}
    @member_profile_categories[0,0] = [["Type..", nil]]

  end

  def sync_results
    @survey = Survey.find_by_id(params[:id])
    @column_matching = []
    @column_unmatching = []
    @column_new = []

    flash[:error] = nil

    metadata_name = Metadatum.includes(:member_profile_category).where(datatype:  "member").pluck(:id, :name, :member_profile_category_id)
    member_metadata_profile_alfa = MemberProfileCategory
    member_metadata_profile_names = member_metadata_profile_alfa.pluck(:id, :name)

    questions = Question.where(survey_id: @survey.id).pluck(:id, :title)


    #read params in case click on delete match button
    delete_match_params = params.select{|p, v| p.include?("delete_m_")}
    #read params in case click on new custom field button
    new_field_params = params.select{|p, v| p.include?("new_field_")}
    #read params in case click on delete field button
    delete_field_params = params.select{|p, v| p.include?("delete_field_")}
    #read params in case click on match field button
    btn_match = params.select{|p, v| p.include?("btn_m_new_")}
    #all match params
    match_field_paramas = params.select{|p, v| p.include?("match_")}
    #all new custom fields params
    new_custom_field_params = params.select{|p, v| p.include?("new_custom_field_category_")}
    #all new match params
    new_match_params = params.select{|p, v| p.include?("new_m_")}

    #all your columns name
    your_name_params =  params.select{|p, v| p.include?("your_name_")}
    #all our columns name
    our_name_params =  params.select{|p, v| p.include?("our_name_")}



    our_ids = []

    #prepare column_matching
    match_field_paramas.each do |key, value|
      your_id = key.split('_')[-1].to_i
      our_id = value.to_i
      our_ids << our_id
      your_name = your_name_params.select{|p, v| p.split('_')[-1].to_i == your_id}.permit!.to_h.first[1]
      our_name = our_name_params.select{|p, v| p.split('_')[-1].to_i == our_id}.permit!.to_h.first[1]
      @column_matching << {your_id: your_id, your_name: your_name, our_id: our_id, our_name: our_name}
    end

    #prepare column_unmatching
    new_match_params.each do |key, value|
      your_id = key.split('_')[-1].to_i
      your_name = your_name_params.select{|p, v| p.split('_')[-1].to_i == your_id}.permit!.to_h.first[1]
      @column_unmatching << {your_id: your_id, your_name: your_name, our_id: nil, our_name: nil}
    end

    #prepare column_new
    new_custom_field_params.each do |key, value|
      your_id = key.split('_')[-1].to_i
      your_name = your_name_params.select{|p, v| p.split('_')[-1].to_i == your_id}.permit!.to_h.first[1]
      @column_new << {your_id: your_id, your_name: your_name, our_id: nil, our_name: nil}
    end

    #available custom fields to match
    @options_for_unmachting = []
    @options_for_unmachting_final = {}
    @options_for_unmachting_final["Do not import"] = [["Skip Custom Field", "skip"]]
    @options_for_unmachting_final["New Custom Field"] = [["Create Custom Field", "new"]]


    metadata_name.each do |m|
      if !our_ids.any?{|o| o == m[0]}
        if m[2].present?

app/views/surveys/_description.html.haml
.col-xs-12.col-lg-12.d-flex.add-margin-top-10.description#description{style:"border-radius:4px", class: "#{f.object.present? and f.object.description.present? ? "background_light_grey previewing" : "empty_description"}"}
  .col-xs-9.col-lg-9.description_preview
    .row.editable#description_edit
      .col-xs-2.no_padding_right{style: "width: 120px"}
        %b.font_size_16 Descriere
      .col-xs-10.form-group
        = f.text_area :description, value: f.object.description, class: 'form-control custom_survey_text', placeholder: "Introduceti descrierea"
    .row.add_padding_left_30
      %b.font_size_18.preview#description_text_content #{f.object.try(:description)}
  .col-xs-3.col-lg-3.pull-right
    %button.pull-right.btn_survey.btn_save.hidden#btn_save_description{type: "button", "data-type"=>"description"}
      %i.fa.fa-check.color_survey_green.add-margin-right-5
      Salveaza
      %button.pull-right.btn_survey.btn_edit#btn_edit_description{type: "button", "data-type"=>"description"}
        %i.fa.fa-pencil.color_survey_lightskyblue.add-margin-right-5
        Editeaza
      %button.pull-right.btn_survey.btn_delete#btn_delete_description{type: "button", "data-type"=>"description", data: { confirm: "Are you sure?" }}
        %i.fa.fa-trash.color_survey_red.add-margin-right-5
        Sterge

app/views/surveys/_form.html.haml
.row
  .col-12.no_padding_left
    = link_to "Pagina principala", root_path, :method => :get, class: "top_link_grey"
    %i.fa.fa-chevron-right.color_grey
    = link_to "Scenarii", surveys_path, :method => :get, class: "top_link_grey"
    %i.fa.fa-chevron-right.color_grey
    %span.color_purple #{form_type} Scenariu

= form_for([@customer, @survey], html: { class: "custom_flex_fist_position", id: "surveys_form_container" }) do |f|
  .row.custom_flex_fist_position.height_100.add-margin-all-0
    .col-lg-12.height_100{style: "margin-bottom: 100px"}
      .row
        .col-lg-12
          - add_error(@survey.errors.full_messages.to_sentence, 'error') if @survey.errors.present?

          .row
            = render partial: 'title', locals: {:f => f}
          .row
            = render partial: 'description', locals: {:f => f}
            .col-xs-12.add-margin-left-10
              %button.pull-left.btn_survey.btn_description#btn_description{class: ("hidden" if f.object.try(:description).present?), type: "button"}
                %i.fa.fa-plus.add-margin-right-5
                %span.add_padding_10 Adauga descriere
          .row.add-margin-top-40.add_padding_left_20#question_list
            .col-xs-12.col-lg-12.no_padding.no_margin_right
              = f.fields_for :questions, f.object.questions.present? ? f.object.questions : [Question.new(order: 1, question_type: "free_text")] do |question|
                = render "question_fields", f: question
              .add_padding_left_10#disable_sortable_new_question_btn
                = link_to_add_association 'Adauga intrebare', f, :questions, class: "pull-left btn_survey btn_delete btn_question btn_new_question add-margin-right-5", style:"border-radius:4px"

          = hidden_field_tag :survey_id,"", value: @survey.id, autocomplete: "off", class: "form-control custom_input"

  .row.fixed_survey_bar.add_margin_top_20
    .col-xs-12.col-sm-12
      .add-margin-right-0.pull-right
        = f.submit yield(:button_text), class: "btn btn-default custom_btn btn_big_custom btn_orange", value: "Salveaza", id: "btn_save_survey", data: {disable_with: "Se salveaza..."}
      .add-margin-right-0.pull-left

:javascript
  window.crm.surveys.init();

app/views/surveys/_free_text.html.haml
.col-lg-6.add_padding_left_25
  .form-group.add_padding_left_30
    = text_field_tag '', nil, class: "free_text form-control add-margin-left-10 option_input_field_form input_field_form", disabled: true, id: "free_text_question_option_#{f.object.try(:order) || ((f.try(:index).to_i || 0) + 1)}"

app/views/surveys/_multiple_answers.html.haml
- options_list = (f.object.options.present? && f.object.question_type == "multiple_answers") ? f.object.options : [Option.new(order: 1), Option.new(order: 2), Option.new(order: 3)]
= f.fields_for :options, options_list do |option|
  = render partial: "option_fields_multiple_answers", locals: {f: option, q: q, is_template: false}
.col-lg-6
  = link_to_add_association 'Adauga optiune', f, :options, partial: 'option_fields_multiple_answers', render_options: {locals: {q: q, is_template: true}}, class: "editable pull-right btn_survey btn_delete btn_question btn_new_option fa fa-plus-sign add-margin-right-5"

app/views/surveys/_multiple_choice.html.haml
- list = f.object.options.present? ? f.object.options : [Option.new(order: 1, title:'1'), Option.new(order: 2, title:'2'), Option.new(order: 3, title:'3'), Option.new(order: 4, title:'4'), Option.new(order: 5, title:'5')]
- options_list = (f.object.options.present? && f.object.question_type == "multiple_choice") ? f.object.options : list
= f.fields_for :options, options_list do |option|
  = render partial: "option_fields_multiple_choice", locals: {f: option, q: q, is_template: false}
.col-lg-6
  = link_to_add_association 'Adauga optiune', f, :options, partial: 'option_fields_multiple_choice', render_options: {locals: {q: q, is_template: true}}, class: "editable pull-right btn_survey btn_delete btn_question btn_new_option fa fa-plus-sign add-margin-right-5"

app/views/surveys/_option_fields_multiple_answers.html.haml
.row.no-margin
  .col-xs-12.col-lg-12.d-flex.option_form.nested-fields
    .col-xs-1.form_size.question_rank.text-center.no_margin_right.no_padding_right
      = check_box_tag '', false, false, disabled: true, class: "radio-primary checkbox_option"
    .col-xs-8.col-lg-8.input_field_form.no_padding
      .form-group
        %span.option_title_preview.preview
          = f.object.try(:title)
        = f.text_field :title, class: "editable form-control input_field_for option_input"
        = f.hidden_field :order
    .col-xs-2.col-lg-2
      = link_to_remove_association "", f, class: "editable pull-left btn_survey_option fa fa-trash color_survey_red add-margin-right-5", id: "btn_delete_#{q.object.try(:order)}_option_#{f.object.try(:order)}"

app/views/surveys/_option_fields_multiple_choice.html.haml
.row.no-margin
  .col-xs-12.col-lg-12.d-flex.option_form.nested-fields
    .col-xs-1.form_size.question_rank.text-center.no_margin_right.no_padding_right
      = radio_button_tag "", false, false, disabled: true, class: "radio_button"
    .col-xs-1.no_padding.no_padding_left
      .form-group
        %span.option_title_preview.preview.add_padding_top_5
          = f.object.try(:title)
        = f.text_field :title, class: "editable form-control aux_title_mc option_input option_input_field_form"
        = f.hidden_field :order
    .col-xs-3.col-lg-3.no_padding.no_padding_left
      .form-group
        %span.option_aux_title_preview.preview.add_padding_top_5
          = f.object.try(:aux_description)
        = f.text_field :aux_description, class: "editable form-control option_input option_input_field_form aux_description"
    .col-xs-2.col-lg-1
      = link_to_remove_association "", f, class: "editable pull-left btn_survey_option no_margin_right_left fa fa-trash color_survey_red add-margin-right-5"

app/views/surveys/_question_fields.html.haml
.row.question.add-margin-top-10.nested-fields{ class:"question_sortable_default_class #{(f.object.try(:id).blank? ? "editing background_grey" : "previewing background_light_grey")}", id: "question_#{f.object.try(:order) || ((f.try(:index).to_i || 0) + 1)}", style:"border-radius:4px"}
  .col-xs-12.col-lg-12.d-flex.add_padding_left_10.no_padding.add-margin-bottom-15{style: "min-height: 60px"}
    .col-xs-1.no_padding_right.question_title{style: "width: 75px"}
      %b.question_rank_title
        = "#{f.object.try(:order) || ((f.try(:index).to_i || 0) + 1)}"
    .col-xs-6.col-lg-6.question_title.no_padding_left.editable
      .input_field_form.form-group.question_title_text_form
        = f.text_field :title, class: 'form-control custom_input question_name_input', placeholder: "Introduceti intrebarea"
    .col-xs-8.col-md-8.col-lg-8.question_title.no_padding_left.preview
      %b.add_padding_top_5.question_title_preview
        = f.object.try(:title)
    .col-xs-2.col-lg-3.no_padding.question_select.editable
      .form-group
        = f.select :question_type, options_for_select(options_for_survey_questions, selected: f.try(:object).question_type || "free_text"), {}, class: 'question_type form-control select2'
    .col-xs-2.col-lg-2.pull-right.add_padding_right_10.no_padding_left{style: "width:210px"}
      %button.preview.pull-right.btn_survey.btn_edit.btn_edit_question{type: "button", "data-type"=>"question"}
        %i.fa.fa-pencil.color_survey_lightskyblue.add-margin-right-5
        Editeaza
      %button.editable.pull-right.btn_survey.btn_save.btn_save_question{type: "button", "data-type"=>"question"}
        %i.fa.fa-check.color_survey_green.add-margin-right-5
        Salveaza

      = link_to_remove_association "Sterge", f, class: "pull-right btn_survey btn_delete link btn_question btn_delete_question color_survey_red add-margin-right-5", data: { confirm: "Sunteti sigur/a?" }, style: ""

  = f.hidden_field :id
  = f.hidden_field :order, value: f.object.try(:order), class: "order_number"


  .col-xs-12.col-lg-12.add_padding_left_15.free_text_field{class: ( "hidden" if f.object.try(:question_type).present? && f.object.try(:question_type) != "free_text")}
    = render "free_text", f: f
  .col-xs-12.col-lg-12.multiple_choice_fields{class: ( "hidden" if f.object.try(:question_type) != "multiple_choice")}
    = render partial: "multiple_choice", locals: {f: f, q: f}
  .col-xs-12.col-lg-12.multiple_answers_fields{class: ( "hidden" if f.object.try(:question_type) != "multiple_answers")}
    = render partial: "multiple_answers", locals: {f: f, q: f}

app/views/surveys/_title.html.haml
.col-xs-12.col-lg-12.d-flex.no_padding_top.title.previewing.background_light_grey.add_margin_top_20#title{style:"border-radius:4px"}
  .col-xs-8.col-lg-8.add-margin-top-20
    .row.editable#title_edit
      .col-xs-7.add-margin-top-10.question_title
        .input_field_form.form-group.question_title_text_form
          = f.text_field :title, value: (f.object.try(:title) || "Scenariul x"), class: 'form-control custom_input', placeholder: "Introduceti titlul"
    .row.preview.add_padding_left_30
      %b.add-margin-bottom-10.add-margin-left-15#title_text_content #{f.object.try(:title).present? ? f.object.try(:title) : "Scenariul x"}
  .col-xs-4.col-lg-4.pull-right.add-margin-top-10
    .form-group.add-margin-top-15
      %button.pull-right.add-margin-top-10.btn_survey.btn_save.hidden#btn_save_title{type: "button", "data-type"=>"title"}
        %i.fa.fa-check.color_survey_green.add-margin-right-5
        Salveaza
    .form-group.add-margin-top-15
      %button.pull-right.add-margin-top-10.btn_survey.btn_edit#btn_edit_title{type: "button", "data-type"=>"title"}
        %i.fa.fa-pencil.color_survey_lightskyblue.add-margin-right-5
        Editeaza

app/views/surveys/edit.html.haml
.surveys
  = render partial: 'surveys/form', locals: {:form_type => "Editeaza"}



:javascript
  window.crm.surveys.init();

app/views/surveys/index.html.haml
.row
  .col-12.no_padding_left
    = link_to "Pagina principala", root_path, :method => :get, class: "top_link_grey"
    %i.fa.fa-chevron-right.color_grey
    %span.color_purple Scenarii
.col-lg-12.add_margin_top_20#survey_index_container{style:"margin-bottom:100px"}
  - if @surveys.blank?
    Nu exista scenarii.
  - else
    - @surveys.each do |survey|
      .row.add_margin_top_10.add_padding_bottom_10.border_custom.add_padding_top_15
        .col-xs-12.col-lg-3
          %h4.bold{style: "width: 500px"}
            #{survey.title}
        .col-xs-12.col-lg-3.d-flex.flex-column

          #{survey.author}
          %span{style: "font-size:11px; font-style: italic; color: lightgray;"} Autor
        .col-xs-12.col-lg-3.d-flex.flex-column
          %span.add_padding_left_20 #{(@survey_brochures[survey.id] || []).count}
          %span{style: "font-size:11px; font-style: italic; color: lightgray;"} Brosuri
        .col-xs-12.col-lg-2
          = link_to "", survey_path(id: survey.id), method: :delete, data: { confirm: "Esti sigur?" }, "data-remote" => "true", class: "fa fa-trash color_red font_size_30 pull-right", "data-toggle" => "tooltip", title: "Sterge"
          - disable_check =  ((@survey_brochures[survey.id] || []).count == 0)
          - if (@survey_brochures[survey.id] || []).count == 0
            %a.fa.fa-pencil.color_lightskyblue.font_size_30.pull-right.add_margin_right_15{href: edit_survey_path(id: survey.id, id: survey.id), method: :get, "data-toggle" => "tooltip", title: "Editeaza"}
              %label{style:'width:18px!important;height:20px'}
          - else
            %span.fa.fa-pencil.color_lightskyblue.disabled.font_size_30.pull-right.add_margin_right_15{"data-toggle" => "tooltip"}
              %i.fa.fa-info-circle.color_black.font_size_18.cursor_pointer{'data-toggle' => "tooltip", title: "Scenariul a fost deja trimis si nu mai poate fi editat!"}
          %a.fa.fa-eye.color_purple.font_size_30.pull-right.add_margin_right_15{href: survey_path(id: survey.id, id: survey.id), method: :get, "data-toggle" => "tooltip", title: "Previzualizare"}

.row.fixed_survey_bar.background_light_grey
  .col-xs-12.col-sm-12
    .btsp_custom_tabs_menu
    .add-margin-right-0.pull-right
      = link_to  "Scenariu nou", new_survey_path(@customer), class:"btn btn-default btn_big_custom custom_btn btn_orange"
    .add-margin-right-0.pull-left



:javascript
  window.crm.surveys.init();
  window.crm.new_design_shared.applyCustomScrollbar("#survey_index_container");

app/views/surveys/new.html.haml
.surveys
  = render partial: 'surveys/form', locals: {:form_type => "Adauga"}



:javascript
  window.crm.surveys.init();

app/views/surveys/show.html.haml
.row{style: "margin-bottom: 100px !important"}
  .col-xs-2.col-sm-2.col-md-2.col-lg-2
  .col-xs-8.col-sm-8.col-md-8.col-lg-8.no_padding.add-margin-all-0.answer_body
    .row.background_white
      .col-lg-12.col-xs-12.no_padding.add-margin-bottom-8
        %img.banner{src: @banner_url}
      .container-fluid#answer_survey_container
        .row.answer_form
          = render partial: 'surveys/answers/answer_form', locals: {questions: @questions, survey: @survey}

  .col-xs-2.col-sm-2.col-md-2.col-lg-2
.row.fixed_survey_bar.background_light_grey
  .col-xs-12.col-sm-12
    .btsp_custom_tabs_menu
    .add-margin-right-0
      %a.btn.btn-default.btn_orange.custom_btn.btn_big_custom{href: surveys_path(id: @survey.id), method: :get, "data-toggle" => "tooltip", id: "btn_save_answer"} Inapoi